/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'MyApp.view.MainViewViewModel',
        'MyApp.view.MainViewViewController',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.CheckboxGroup',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.selection.RowModel',
        'Ext.grid.plugin.CellEditing'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },
    itemId: 'mainView',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            height: 100,
            itemId: 'headerPanel',
            title: 'Header'
        },
        {
            xtype: 'panel',
            flex: 1,
            region: 'west',
            split: true,
            itemId: 'leftPanel',
            width: 150,
            title: '',
            items: [
                {
                    xtype: 'container'
                },
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: 'Date cursant',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Nume',
                            name: 'numeCursant',
                            allowBlank: false,
                            maxLength: 40,
                            maxLengthText: 'Text too long. The text must not exceed 40 characters.',
                            minLength: 3,
                            minLengthText: 'Text too short. The text must have at least 3 characters.'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Prenume',
                            name: 'prenumeCursant',
                            allowBlank: false,
                            maxLength: 40,
                            maxLengthText: 'Text too long. The text must not exceed 40 characters.',
                            minLength: 3,
                            minLengthText: 'Text too short. The text must have at least 3 characters.'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Adresa',
                            name: 'adresaCursant',
                            allowBlank: false,
                            maxLength: 50,
                            maxLengthText: 'Text too long. The text must not exceed 50 characters.',
                            minLength: 10,
                            minLengthText: 'Text too short. The text must have at least 10 characters.'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'CNP',
                            name: 'cnpCursant',
                            allowBlank: false,
                            maxLength: 13,
                            regex: /[1-9]{13}/
                        },
                        {
                            xtype: 'datefield',
                            anchor: '100%',
                            fieldLabel: 'Data nasterii',
                            name: 'dataNasteriiCursant',
                            invalidText: 'Invalid date',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            showToday: false
                        },
                        {
                            xtype: 'checkboxgroup',
                            width: 150,
                            defaults: {
                                margin: '0 10 0 0'
                            },
                            fieldLabel: 'Categoria',
                            allowBlank: false,
                            blankText: 'You must select at least a category',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    margin: '0 10 0 0',
                                    name: 'A',
                                    value: 'A',
                                    boxLabel: 'A',
                                    inputValue: 'A'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    name: 'B',
                                    value: {
                                        value: 'B'
                                    },
                                    boxLabel: 'B',
                                    inputValue: 'B'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    name: 'C',
                                    value: {
                                        value: 'C'
                                    },
                                    boxLabel: 'C',
                                    inputValue: 'C'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    name: 'CE',
                                    value: {
                                        value: 'CE'
                                    },
                                    boxLabel: 'CE',
                                    inputValue: 'CE'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    name: 'D',
                                    value: {
                                        value: 'D'
                                    },
                                    boxLabel: 'D',
                                    inputValue: 'D'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Submit',
                                    listeners: {
                                        click: 'onButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: 'MyButton'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 1,
            region: 'center',
            split: true,
            itemId: 'rightPanel',
            title: '',
            items: [
                {
                    xtype: 'container'
                },
                {
                    xtype: 'gridpanel',
                    title: 'Cursanti',
                    bind: {
                        store: '{Cursanti}'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'numeCursant',
                            text: 'Nume',
                            flex: 1,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'prenumeCursant',
                            text: 'Prenume',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'adresaCursant',
                            text: 'Adresa',
                            flex: 1
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'cnpCursant',
                            text: 'CNP',
                            flex: 1,
                            format: '0'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'dataNasteriiCursant',
                            text: 'Data nasterii',
                            flex: 1,
                            format: 'd/m/Y'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                var cat = [
                                'A', 'B', 'C', 'CE', 'D'
                                ];

                                var courseCategories = [];
                                for(var i = 0; i<cat.length; i++)
                                {
                                    if(record.get(cat[i]) == 'on')
                                    {
                                        courseCategories.push(cat[i]);
                                    }
                                }
                                return courseCategories.join(', ');
                            },
                            dataIndex: 'categorieCurs',
                            text: 'Categoria',
                            flex: 1
                        }
                    ],
                    selModel: {
                        selType: 'rowmodel',
                        listeners: {
                            select: 'onRowModelSelect'
                        }
                    },
                    plugins: [
                        {
                            ptype: 'cellediting'
                        }
                    ]
                }
            ]
        }
    ]

});